### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by dnacombo** [mne-tools/dipole-simulator#13]
Hi @hoechenberger @agramfort 

This is really nice.
My two cents on how this could evolve:
- the 3d representation of the dipole looks fancy, but isn't super easy to figure out where the dipole actually is. Have you thought of using a glassbrain type of display?
- Sliders are also not really intuitive to move the dipole
- Alex already told me you are trying to improve speed. Indeed, that's crucial :)

Below is a screenshot of what I did in matlab, tweaking FT functions. Interaction is done via clicking in one of the three brain panels. Left button sets the position of the dipole, right button sets its orientation (the tip of the arrow).
A convenient way to speeding things up would also be to have an "update" button, so that I can use a few clicks to set the position and orientation, then draw, when I'm done.

![image](https://user-images.githubusercontent.com/4716235/78362980-4aa6c900-75bb-11ea-9c42-4035aeedcad6.png)

**Comment by hoechenberger** [comment]
Hey, thanks for your quick feedback!

> * the 3d representation of the dipole looks fancy, but isn't super easy to figure out where the dipole actually is. Have you thought of using a glassbrain type of display?

Yes I have, and actually started off displaying slices like you do in your Matlab example, but we then decided to give the 3D "orthoview" a shot first and wait for feedback.

> * Sliders are also not really intuitive to move the dipole

I believe it would certainly be possible to allow users to click on an image to position the dipole. Will look into this.

> * Alex already told me you are trying to improve speed. Indeed, that's crucial :)

Hehe, yes. :)

> 
> Below is a screenshot of what I did in matlab [...] Left button sets the position of the dipole, right button sets its orientation (the tip of the arrow).

Looks great, and good idea to map both mouse buttons!

> A convenient way to speeding things up would also be to have an "update" button, so that I can use a few clicks to set the position and orientation, then draw, when I'm done.

That would be possible. But let's see first if we can speed things up (and / or potentially switch to a different display mode)

Thanks again for your feedback!

**Comment by hoechenberger** [comment]
@dnacombo Please check out the latest revision at:
https://mybinder.org/v2/gh/hoechenberger/dipoles_demo/master?urlpath=voila%2Frender%2Findex.ipynb

It's not yet optimized for drawing speed, but usability should already be much better than in the previous iteration. Please do let me know what you think!

**Comment by hoechenberger** [comment]
Closing now, thanks for your valuable feedback!
